IUBLibTech/datacore

spec/factories/users.rb
spec/presenters/hyrax/data_set_presenter_spec.rb
spec/views/_user_util_links.html.erb_spec.rb

Locally, gets all tests passing and removes a `puts` call.
Marking this WIP because we might want to get CircleCI configured and automatically running against PRs first, and use this PR as the initial test case?

WIP passing tests

---

.circleci/config.yml
Gemfile
Gemfile.lock
config/settings.yml

Various fixes for CircleCI:
- Use correct fcrepo path for the samvera/fcrepo4 image
- Set USER environment variable in Circle that's needed by existing deepblue config patterns and change email address to iu.edu
- Use old style solr 6 API V2 url
- Add gem needed by Circle
- Remove JS spec step

Circle fixes

---

app/forms/hyrax/data_set_form.rb
app/models/concerns/deepblue/default_metadata.rb
app/models/solr_document.rb
app/presenters/hyrax/data_set_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/authorities/resource_types.yml
config/locales/data_set.en.yml
spec/forms/hyrax/data_set_form_spec.rb

Fixes
https://bugs.dlib.indiana.edu/browse/IUSW-1750

Add and remove fields from metadata

---

app/forms/hyrax/data_set_form.rb
app/models/concerns/deepblue/default_metadata.rb
app/models/solr_document.rb
app/presenters/hyrax/data_set_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/locales/data_set.en.yml
spec/forms/hyrax/data_set_form_spec.rb

Refs https://bugs.dlib.indiana.edu/browse/IUSW-1750
Changes the RDF predicate for licensing comments to dcterms:license

Change RDF predicate for license comments

---

app/assets/stylesheets/iu-chimera/_layout.scss
app/assets/stylesheets/main.scss
app/views/_masthead.html.erb

Tweaks to better handle changing app title, and dashboard footer.

UI responsive tweaks

---

.circleci/config.yml

CIRCLECI_USERNAME is not set sometimes, use "circleci" instead

Update circleci ENV setup

---

app/assets/stylesheets/iu-chimera/_footer.scss
app/assets/stylesheets/iu-chimera/_header.scss
app/assets/stylesheets/iu-chimera/_layout.scss
app/assets/stylesheets/iu-chimera/_notifications.scss
app/assets/stylesheets/iu-chimera/_responsive.scss
app/assets/stylesheets/iu-chimera/_vars-colors.scss
app/assets/stylesheets/iu-chimera/styles.scss
app/assets/stylesheets/main.scss
app/assets/stylesheets/mlib-styles.css
app/views/_user_util_links.html.erb
app/views/catalog/_search_form.html.erb
app/views/hyrax/homepage/_home_content.html.erb
app/views/hyrax/static/how-to-upload.html.erb
config/initializers/hyrax.rb
spec/views/_user_util_links.html.erb_spec.rb

Random UI tweaks and typo fixes:
- normalize buttons
- remove search drop-down filter
- fix badge positions
- remove analytics
- remove incorrectly commented featured researcher code
- use IU-style notifications button
- use IU-style fonts and colors in header and footer
- fix responsiveness of header menus

UI tweaks and typo fixes 1

---

lib/tasks/ingest_files.rake

Rake task for sideloading files into preexisting datasets.

Ingest files

---

app/services/deepblue/doi_minting_service.rb
app/views/_logo.html.erb
app/views/hyrax/static/about.html.erb
app/views/shared/_footer.html.erb
config/locales/data_set.en.yml
config/locales/deepblue.en.yml

**Footer**
Updates copyright year
**Michigan --> Indiana**
For `grantnumber` field description, replaces:
_If you have one, provide the grant number that was assigned by the University of Michigan’s Office of Research and Sponsored Projects (ORSP)._
with:
...by Indiana University's Office of Research Administration
Replaces "University of Michigan" with "Indiana University" as `PUBLISHER` value in DOI Minting Service.
**Link text**
On the "About" page, replaces raw link text:
Data on human subjects or sensitive data. This includes data that are subject to export controls, present a conflict of interest for the University or the Researcher(s), or whose distribution would otherwise constitute a violation of research ethics or compliance. For HIPAA-aligned data storage options, see: …

Language changes

---

app/controllers/archive_controller.rb
app/models/archive_file.rb
app/models/archive_file_worker.rb
config/settings.yml
lib/tasks/download_archival_files.rake

* adds configuration for limiting archive request jobs:
* by job count, filtered by status
* by current disk space used
* refactors much of `DownloadArchivalFilesTask` into `ArchiveFileWorker`

[IUS-1889] [IUS-2220] add throttling config, ArchiveFileWorker helper

---

.gitignore
app/controllers/archive_controller.rb
app/models/archive_file.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/hyrax/file_sets/_show_details.html.erb
app/views/hyrax/file_sets/media_display/_audio.html.erb
app/views/hyrax/file_sets/media_display/_default.html.erb
app/views/hyrax/file_sets/media_display/_image.html.erb
app/views/hyrax/file_sets/media_display/_office_document.html.erb
app/views/hyrax/file_sets/media_display/_pdf.html.erb
app/views/hyrax/file_sets/media_display/_video.html.erb
app/views/hyrax/file_sets/show.html.erb
lib/extensions/hyrax/downloads_controller/variable_download_sourcing.rb

* FileSet download links on work show page now redirect to FileSet show page
* removed download link on FileSet show page
* add button on FileSet show page to explicitly request file from archive server

[IUS-2220] centralize archive file requests on FileSet page

---

.env.example
.gitignore
Gemfile
Gemfile.lock
app/controllers/archive_controller.rb
app/models/archive_file.rb
app/models/archive_file_worker.rb
app/presenters/concerns/datacore/presents_archive_file.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/hyrax/file_sets/show.html.erb
config/settings.yml
lib/tasks/download_archival_files.rake
lib/tasks/ingest_files.rake

Adds configurable requirement of recaptcha and/or user sign-in

[IUS-2220] optionally support recaptcha

---

config/routes.rb

blocks controller actions that generate guest accounts in users table

block blacklight bookmarks in routing

---

lib/extensions/extensions.rb
lib/extensions/qa/authorities/collections/collections_search.rb
spec/authorities/qa/authorities/collections_spec.rb
spec/factories/collection_types.rb
spec/factories/collections.rb
spec/factories/object_id.rb

Cherry-picked from essi.
Changes collection authority search to search on partial matches, instead of exact whole-word matches, only.

[IUS-2584] collection auto-suggest wildcard matching

---

app/views/hyrax/static/about.html.erb

[IUS-2578] update knowledge base link in documentation 

---

app/views/_logo.html.erb
app/views/hyrax/homepage/_featured_links.html.erb
app/views/hyrax/homepage/_home_content.html.erb
app/views/hyrax/homepage/_marketing.html.erb
config/locales/deepblue.en.yml
config/locales/hyrax.en.yml

Updated homepage text
Added Documentation tab to Featured Works and Recent Updates tabs
Deleted old unused files

IUS-2596 Updating Homepage

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js

See related hyrax issue, pr:
https://github.com/samvera/hyrax/issues/6826
https://github.com/samvera/hyrax/pull/6762
_In draft status pending review of datacore overrides of hyrax javascript, and which ones to retain/drop/modify_
Note that deployment requires installing bundle, clobbering and recompiling assets

[IUS-2628] fix broken javascript

---

README.md

Updated the README.md file for IU DataCORE

[IUS-2592] update GitHub readme file

---

app/controllers/robots_controller.rb
app/views/hyrax/dashboard/sidebar/_configuration.html.erb
app/views/robots/_form.html.erb
app/views/robots/edit.html.erb
config/routes.rb
public/robots.txt
spec/controllers/robots_controller_spec.rb

Copied from https://github.com/IU-Libraries-Joint-Development/essi/pull/590

[IUS-2617] [IUS-2635] add dynamic robots.txt support

---

app/assets/stylesheets/main.scss
config/locales/hyrax.en.yml

Made changes to a  .scss file
Added text to config/locales/hyrax.en.yml - for the page filter dropdowns

IUS-2581 aligning UI components

---

Gemfile
Gemfile.lock
app/controllers/rack_attacks_controller.rb
app/views/hyrax/dashboard/sidebar/_configuration.html.erb
app/views/rack_attacks/_form.html.erb
app/views/rack_attacks/edit.html.erb
app/views/robots/edit.html.erb
config/initializers/rack_attack.rb
config/routes.rb
config/settings.yml
lib/datacore/rack_attack_config.rb

Adds rack attack gem and dynamic configuration accessible via the UI.  Copied from essi.

[IUS-2617] [IUS-2636] add rack attack and dynamic configuration

---

app/views/hyrax/file_sets/_show_archive_file.html.erb

Adding html attribute tags to clarify which label belongs to which field in the form.

IUS-2639 Improve Archived File email field label for accessibility

---

app/services/deepblue/log_reader.rb
app/services/deepblue/yaml_populate_service.rb
spec/jobs/about_to_expire_embargoes_job_spec.rb
spec/mailers/deepblue_mailer_spec.rb
spec/services/dataset/date_coverage_service_spec.rb
spec/services/deepblue/about_to_expire_embargoes_service_spec.rb
spec/services/deepblue/deactivate_expired_embargoes_service_spec.rb
spec/services/deepblue/log_exporter_spec.rb
spec/services/deepblue/log_reader_spec.rb
spec/services/deepblue/log_reporter_spec.rb
spec/services/deepblue/virus_scan_service_spec.rb
spec/services/deepblue/yaml_populate_service_spec.rb

Additional unit testing for the app/services/deepblue directory.
Plus a few small changes to the code to make unit testing easier.

IUS-2613 Deepblue services unit tests

---

app/views/bulkrax/exporters/index.html.erb
app/views/bulkrax/importers/index.html.erb
app/views/hyrax/admin/appearances/show.html.erb
app/views/hyrax/base/_form_member_of_collections.html.erb
app/views/hyrax/dashboard/profiles/show.html.erb
lib/extensions/extensions.rb
lib/extensions/hyrax/collapsable_section_presenter/collapsable_section_presenter_behavior.rb

Adding aria-label attributes to form fields for the benefit of site users using screen readers.

IUS-2626 screen reader html aria-label attributes

---

app/views/rack_attacks/_form.html.erb
app/views/rack_attacks/edit.html.erb
config/initializers/rack_attack.rb
lib/datacore/rack_attack_config.rb

[IUS-2617] iterating on rack attack

---

app/views/hyrax/static/_help_sidebar.html.erb
app/views/hyrax/static/about.html.erb
app/views/hyrax/static/datacore-documentation-guide.html.erb
app/views/hyrax/static/datacore-glossary.html.erb
app/views/hyrax/static/file-format-preservation.html.erb
app/views/hyrax/static/help.html.erb
app/views/hyrax/static/how-to-upload.html.erb
app/views/hyrax/static/management-plan-text.html.erb
app/views/hyrax/static/metadata-guidance.html.erb
app/views/hyrax/static/prepare-your-data.html.erb
app/views/hyrax/static/retention.html.erb
app/views/hyrax/static/terms.html.erb
app/views/hyrax/static/use-downloaded-data.html.erb
config/routes.rb

Also fixed a couple of misspellings.

[IUS-2738] DataCORE - Update static page names

---

Gemfile
Gemfile.lock
config/settings/test.yml
spec/models/ability_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb

* adds gem support for feature testing
* adds record (database, fedora, solr) cleaning around suite, optional `:clean` parameter for groups
* updates Ability spec to run in new clean context
* adds optional spec order randomization

[IUS-2749] rspec record cleanup
